version: "3.9"

services:
  web:
    container_name: web

    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - ".:/app"
      - "/app/node_modules"

    environment:
      - HOST=0.0.0.0
      - PORT=3000

    ports:
      - "3000:3000"
