name: "ci"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node and yarn
        uses: mskelton/setup-yarn@v1
        with:
        node-version: "16.x"

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn run test:unit
